# Generated by Django 5.2.10 on 2026-01-12 20:09

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CRSDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название СК')),
                ('epsg_code', models.IntegerField(blank=True, null=True, verbose_name='Код EPSG')),
                ('proj4_definition', models.TextField(blank=True, verbose_name='Определение Proj4')),
                ('is_custom', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Система координат',
                'verbose_name_plural': 'Системы координат',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название организации')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/', verbose_name='Логотип')),
                ('primary_color', models.CharField(default='#2196f3', max_length=7, verbose_name='Основной цвет')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.CreateModel(
            name='ProjectTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название шаблона')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('default_tags', models.JSONField(blank=True, default=list, verbose_name='Теги по умолчанию')),
                ('default_quality', models.CharField(default='MEDIUM', max_length=20, verbose_name='Качество по умолчанию')),
                ('default_target_gsd', models.FloatField(blank=True, null=True, verbose_name='Целевой GSD по умолчанию')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Шаблон проекта',
                'verbose_name_plural': 'Шаблоны проекта',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Архивирован'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Публичный'),
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.JSONField(blank=True, default=list, verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='project',
            name='target_gsd',
            field=models.FloatField(blank=True, null=True, verbose_name='Целевой GSD (см/пикс)'),
        ),
        migrations.AddField(
            model_name='task',
            name='quality_preset',
            field=models.CharField(default='MEDIUM', max_length=20, verbose_name='Настройка качества'),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255, verbose_name='Действие')),
                ('details', models.TextField(blank=True, verbose_name='Детали')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Лог активности',
                'verbose_name_plural': 'Логи активности',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст заметки')),
                ('annotation_type', models.CharField(choices=[('MAP', 'Карта'), ('MODEL_3D', '3D Модель')], max_length=20, verbose_name='Тип')),
                ('position', models.JSONField(verbose_name='Позиция')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='core.project')),
            ],
            options={
                'verbose_name': 'Аннотация',
                'verbose_name_plural': 'Аннотации',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DetectedObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(choices=[('VEHICLE', 'Транспорт'), ('BUILDING', 'Здание'), ('TREE', 'Дерево'), ('OTHER', 'Прочее')], max_length=20, verbose_name='Тип объекта')),
                ('confidence', models.FloatField(verbose_name='Уверенность')),
                ('location', models.JSONField(verbose_name='Местоположение (lat, lon)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detected_objects', to='core.project')),
            ],
            options={
                'verbose_name': 'Обнаруженный объект',
                'verbose_name_plural': 'Обнаруженные объекты',
            },
        ),
        migrations.CreateModel(
            name='FlightPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название миссии')),
                ('altitude', models.FloatField(default=100, verbose_name='Высота полета (м)')),
                ('speed', models.FloatField(default=5, verbose_name='Скорость (м/с)')),
                ('overlap_h', models.IntegerField(default=80, verbose_name='Продольное перекрытие (%)')),
                ('overlap_v', models.IntegerField(default=70, verbose_name='Поперечное перекрытие (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_plans', to='core.project')),
            ],
            options={
                'verbose_name': 'План полета',
                'verbose_name_plural': 'Планы полетов',
            },
        ),
        migrations.CreateModel(
            name='FlightWaypoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waypoints', to='core.flightplan')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GCP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('point_type', models.CharField(choices=[('CONTROL', 'Контрольная точка (GCP)'), ('CHECK', 'Проверочная точка (Check Point)')], default='CONTROL', max_length=10, verbose_name='Тип')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('altitude', models.FloatField(blank=True, null=True, verbose_name='Высота')),
                ('measured_lat', models.FloatField(blank=True, null=True)),
                ('measured_lon', models.FloatField(blank=True, null=True)),
                ('measured_alt', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gcps', to='core.project')),
            ],
            options={
                'verbose_name': 'Опорная точка',
                'verbose_name_plural': 'Опорные точки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MeasuringResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure_type', models.CharField(choices=[('DISTANCE', 'Расстояние'), ('AREA', 'Площадь'), ('VOLUME', 'Объем')], max_length=10, verbose_name='Тип замера')),
                ('value', models.FloatField(verbose_name='Значение')),
                ('unit', models.CharField(max_length=10, verbose_name='Единица измерения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='core.project')),
            ],
            options={
                'verbose_name': 'Замер',
                'verbose_name_plural': 'Замеры',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название ветки')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_main', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='core.project')),
            ],
            options={
                'verbose_name': 'Ветка проекта',
                'verbose_name_plural': 'Ветки проекта',
            },
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_type', models.CharField(choices=[('ORTHOPHOTO', 'Ортофотоплан'), ('DSM', 'Цифровая модель рельефа'), ('MODEL_3D', '3D Модель'), ('POINT_CLOUD', 'Облако точек'), ('NDVI', 'Карта NDVI'), ('REPORT', 'Отчет'), ('KML', 'KML/KMZ Слой'), ('SPECTRAL_BAND', 'Спектральный канал'), ('CONTOUR_LINES', 'Изолинии (Горизонтали)')], max_length=20, verbose_name='Тип артефакта')),
                ('file', models.FileField(upload_to='artifacts/', verbose_name='Файл')),
                ('version', models.IntegerField(default=1, verbose_name='Версия')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Метаданные')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название файла')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='core.project')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='core.task')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='core.projectbranch')),
            ],
            options={
                'verbose_name': 'Артефакт',
                'verbose_name_plural': 'Артефакты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='core.projectbranch'),
        ),
        migrations.CreateModel(
            name='ProjectSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название снимка')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artifacts_count', models.IntegerField(default=0)),
                ('files_count', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='core.project')),
            ],
            options={
                'verbose_name': 'Снимок проекта',
                'verbose_name_plural': 'Снимки проекта',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='core.projecttemplate'),
        ),
        migrations.CreateModel(
            name='ProjectTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('label', models.CharField(blank=True, max_length=255)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.artifact')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='core.project')),
            ],
            options={
                'verbose_name': 'Таймлайн проекта',
                'verbose_name_plural': 'Таймлайн проекта',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='QualityMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gsd', models.FloatField(verbose_name='GSD (см/пикс)')),
                ('rmse_x', models.FloatField(verbose_name='RMSE X (м)')),
                ('rmse_y', models.FloatField(verbose_name='RMSE Y (м)')),
                ('rmse_z', models.FloatField(verbose_name='RMSE Z (м)')),
                ('overlap_mean', models.FloatField(verbose_name='Среднее перекрытие (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_metrics', to='core.artifact')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_metrics', to='core.project')),
            ],
            options={
                'verbose_name': 'Метрика качества',
                'verbose_name_plural': 'Метрика качества',
            },
        ),
        migrations.CreateModel(
            name='SurveyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название выезда')),
                ('date', models.DateField(verbose_name='Дата обследования')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='core.project')),
            ],
            options={
                'verbose_name': 'Полевой выезд',
                'verbose_name_plural': 'Полевые выезды',
            },
        ),
        migrations.CreateModel(
            name='SurveyPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Координаты')),
                ('photo', models.ImageField(upload_to='surveys/', verbose_name='Фото')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='core.surveytask')),
            ],
            options={
                'verbose_name': 'Точка обследования',
                'verbose_name_plural': 'Точки обследования',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dark_mode', models.BooleanField(default=True)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('quality_preference', models.CharField(default='MEDIUM', max_length=20)),
                ('language', models.CharField(default='ru', max_length=10)),
                ('data_retention_days', models.IntegerField(default=365, verbose_name='Срок хранения данных (дней)')),
                ('max_projects', models.IntegerField(default=10, verbose_name='Макс. количество проектов')),
                ('max_storage_gb', models.FloatField(default=5.0, verbose_name='Макс. объем хранилища (ГБ)')),
                ('can_use_ai', models.BooleanField(default=True, verbose_name='Доступ к AI анализу')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='core.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WebhookConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='Webhook URL')),
                ('secret', models.CharField(blank=True, max_length=255, verbose_name='Secret Key')),
                ('events', models.JSONField(default=list, verbose_name='Events')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='core.project')),
            ],
            options={
                'verbose_name': 'Вебхук',
                'verbose_name_plural': 'Вебхуки',
            },
        ),
        migrations.CreateModel(
            name='ProjectPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presence', to='core.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('project', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ProjectShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('VIEW', 'Просмотр'), ('EDIT', 'Редактирование')], default='VIEW', max_length=10, verbose_name='Уровень доступа')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='core.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Доступ к проекту',
                'verbose_name_plural': 'Доступы к проектам',
                'unique_together': {('project', 'user')},
            },
        ),
    ]
