# Generated by Django 5.2.10 on 2026-01-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_project_share_password_project_share_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='dsm_resolution',
            field=models.FloatField(blank=True, null=True, verbose_name='Разрешение DSM (см/пикс)'),
        ),
        migrations.AddField(
            model_name='project',
            name='optimize_mesh',
            field=models.BooleanField(default=True, verbose_name='Оптимизировать 3D модель'),
        ),
        migrations.AddField(
            model_name='project',
            name='ortho_resolution',
            field=models.FloatField(blank=True, null=True, verbose_name='Разрешение ортофото (см/пикс)'),
        ),
        migrations.AddField(
            model_name='project',
            name='processing_quality',
            field=models.CharField(default='MEDIUM', max_length=20, verbose_name='Качество обработки'),
        ),
    ]
