# Generated by Django 5.2.10 on 2026-01-14 16:17

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_project_dsm_resolution_project_optimize_mesh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(default='orthophoto', max_length=50, verbose_name='Тип задачи'),
        ),
        migrations.CreateModel(
            name='Orthophoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название ортофото')),
                ('file_path', models.CharField(max_length=500)),
                ('bounds', django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='Границы для отображения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolution', models.FloatField(verbose_name='GSD в метрах')),
                ('tiles_url', models.CharField(blank=True, max_length=500)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orthophotos', to='core.project')),
            ],
            options={
                'verbose_name': 'Ортофотоплан',
                'verbose_name_plural': 'Ортофотопланы',
                'db_table': 'orthophotos',
            },
        ),
    ]
